web:
  build: .
  command: rackup -o 0.0.0.0
  volumes:
    - .:/myapp
  ports:
    - "9292:9292"
  links:
    - redis
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
redis:
  image: redis:latest